<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Login extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('owner_model');
		$this->load->model('karyawan_model');
	}

	public function index()
	{
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('home');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login');
		}
		else
		{
			$jabatan = $this->input->post('jabatan');
			$username = $this->input->post('username');
			if($jabatan==1){
				$owner = $this->owner_model->ambil_data_id($username);

				if(strtolower($this->input->post('username')) == $owner->id_owner  &&
					$this->input->post('password') == $owner->password)
					
				{
					$this->session->set_userdata('logined', $this->input->post('username'));

					redirect("home/index_owner");
				}

				else 
				{
					redirect("/");
				}

			}
			
			elseif($jabatan==2){
				$karyawan = $this->karyawan_model->select_karyawan($username);

				if(strtolower($this->input->post('username')) == $karyawan->id_karyawan  &&
					$this->input->post('password') == $karyawan->password)
					
				{
					$this->session->set_userdata('logined', $this->input->post('username'));

					redirect("home/index");
				}
				else 
				{
					redirect("/");

				}
			}
			else{
				redirect("/");
			}
		}
	} 
	
	public function logout()
	{
		$this->session->unset_userdata('logined');
		redirect("/");
	} 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */